//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryData()
        {
            this.SectionDatas = new HashSet<SectionData>();
        }
    
        public int CategoryID { get; set; }
        public int CategoryOrder { get; set; }
        public int AssessmentID { get; set; }
        public int CatID { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionData> SectionDatas { get; set; }
        public virtual Category Category { get; set; }
    }
}
