//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupData()
        {
            this.QuestionDatas = new HashSet<QuestionData>();
        }
    
        public int GroupID { get; set; }
        public int GroupOrder { get; set; }
        public int SectionID { get; set; }
        public int GroID { get; set; }
        public Nullable<int> GroupScore { get; set; }
    
        public virtual SectionData SectionData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionData> QuestionDatas { get; set; }
        public virtual Group Group { get; set; }
    }
}
