//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustryTarget
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int SectionID { get; set; }
        public int IndustryID { get; set; }
        public string Score { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Section Section { get; set; }
        public virtual IndustryTargetScoreValue IndustryTargetScoreValue { get; set; }
    }
}
