//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OwaspSAMMContext : DbContext
    {
        public OwaspSAMMContext()
            : base("name=OwaspSAMMContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentTemplate> AssessmentTemplates { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<CategoryData> CategoryDatas { get; set; }
        public virtual DbSet<GroupData> GroupDatas { get; set; }
        public virtual DbSet<QuestionData> QuestionDatas { get; set; }
        public virtual DbSet<SectionData> SectionDatas { get; set; }
        public virtual DbSet<TemplateCategory> TemplateCategories { get; set; }
        public virtual DbSet<TemplateGroup> TemplateGroups { get; set; }
        public virtual DbSet<TemplateQuestion> TemplateQuestions { get; set; }
        public virtual DbSet<TemplateSection> TemplateSections { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<IndustryTarget> IndustryTargets { get; set; }
        public virtual DbSet<IndustryTargetScoreValue> IndustryTargetScoreValues { get; set; }
    }
}
