//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateGroup()
        {
            this.TemplateQuestions = new HashSet<TemplateQuestion>();
        }
    
        public int GroID { get; set; }
        public int GroupID { get; set; }
        public int GroupOrder { get; set; }
        public int SectionID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual TemplateSection TemplateSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateQuestion> TemplateQuestions { get; set; }
    }
}
