//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateQuestion
    {
        public int QueID { get; set; }
        public int QuestionID { get; set; }
        public int QuestionOrder { get; set; }
        public int GroupID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual TemplateGroup TemplateGroup { get; set; }
    }
}
