//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwaspSAMM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserData()
        {
            this.Assessments = new HashSet<Assessment>();
            this.Assessments1 = new HashSet<Assessment>();
            this.Assessments2 = new HashSet<Assessment>();
        }
    
        public int UserID { get; set; }
        public string UserNTID { get; set; }
        public string UserDomain { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string ManagerID { get; set; }
        public string MgrLastName { get; set; }
        public string MgrFirstName { get; set; }
        public string ManagerEID { get; set; }
        public string OrgName { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<bool> Administrator { get; set; }
        public Nullable<bool> Manager { get; set; }
        public string BusinessUnit { get; set; }
        public Nullable<bool> BUOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment> Assessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment> Assessments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment> Assessments2 { get; set; }
    }
}
